from app.database import enums

to_stat_enum = {
    "Vitality": enums.Stat.VITALITY,
    "AP": enums.Stat.AP,
    "MP": enums.Stat.MP,
    "Initiative": enums.Stat.INITIATIVE,
    "Prospecting": enums.Stat.PROSPECTING,
    "Range": enums.Stat.RANGE,
    "Summons": enums.Stat.SUMMON,
    "Wisdom": enums.Stat.WISDOM,
    "Strength": enums.Stat.STRENGTH,
    "Intelligence": enums.Stat.INTELLIGENCE,
    "Chance": enums.Stat.CHANCE,
    "Agility": enums.Stat.AGILITY,
    "AP Parry": enums.Stat.AP_PARRY,
    "AP Reduction": enums.Stat.AP_REDUCTION,
    "MP Parry": enums.Stat.MP_PARRY,
    "MP Reduction": enums.Stat.MP_REDUCTION,
    "Critical": enums.Stat.CRITICAL,
    "Heals": enums.Stat.HEALS,
    "Lock": enums.Stat.LOCK,
    "Dodge": enums.Stat.DODGE,
    "Power": enums.Stat.POWER,
    "Damage": enums.Stat.DAMAGE,
    "Critical Damage": enums.Stat.CRITICAL_DAMAGE,
    "Neutral Damage": enums.Stat.NEUTRAL_DAMAGE,
    "Earth Damage": enums.Stat.EARTH_DAMAGE,
    "Fire Damage": enums.Stat.FIRE_DAMAGE,
    "Water Damage": enums.Stat.WATER_DAMAGE,
    "Air Damage": enums.Stat.AIR_DAMAGE,
    "Reflect": enums.Stat.REFLECT,
    "Trap Damage": enums.Stat.TRAP_DAMAGE,
    "Power (traps)": enums.Stat.TRAP_POWER,
    "Pushback Damage": enums.Stat.PUSHBACK_DAMAGE,
    "% Spell Damage": enums.Stat.PCT_SPELL_DAMAGE,
    "% Weapon Damage": enums.Stat.PCT_WEAPON_DAMAGE,
    "% Ranged Damage": enums.Stat.PCT_RANGED_DAMAGE,
    "% Melee Damage": enums.Stat.PCT_MELEE_DAMAGE,
    "% Final Damage": enums.Stat.PCT_FINAL_DAMAGE,
    "Neutral Resistance": enums.Stat.NEUTRAL_RES,
    "% Neutral Resistance": enums.Stat.PCT_NEUTRAL_RES,
    "Earth Resistance": enums.Stat.EARTH_RES,
    "% Earth Resistance": enums.Stat.PCT_EARTH_RES,
    "Fire Resistance": enums.Stat.FIRE_RES,
    "% Fire Resistance": enums.Stat.PCT_FIRE_RES,
    "Water Resistance": enums.Stat.WATER_RES,
    "% Water Resistance": enums.Stat.PCT_WATER_RES,
    "Air Resistance": enums.Stat.AIR_RES,
    "% Air Resistance": enums.Stat.PCT_AIR_RES,
    "Critical Resistance": enums.Stat.CRITICAL_RES,
    "Pushback Resistance": enums.Stat.PUSHBACK_RES,
    "% Ranged Resistance": enums.Stat.PCT_RANGED_RES,
    "% Melee Resistance": enums.Stat.PCT_MELEE_RES,
    "pods": enums.Stat.PODS,
}

to_effect_enum = {
    "Neutral damage": enums.WeaponEffectType.NEUTRAL_DAMAGE,
    "Earth damage": enums.WeaponEffectType.EARTH_DAMAGE,
    "Fire damage": enums.WeaponEffectType.FIRE_DAMAGE,
    "Water damage": enums.WeaponEffectType.WATER_DAMAGE,
    "Air damage": enums.WeaponEffectType.AIR_DAMAGE,
    "Neutral steal": enums.WeaponEffectType.NEUTRAL_STEAL,
    "Earth steal": enums.WeaponEffectType.EARTH_STEAL,
    "Fire steal": enums.WeaponEffectType.FIRE_STEAL,
    "Water steal": enums.WeaponEffectType.WATER_STEAL,
    "Air steal": enums.WeaponEffectType.AIR_STEAL,
    "AP": enums.WeaponEffectType.AP,
    "MP": enums.WeaponEffectType.MP,
    "HP restored": enums.WeaponEffectType.HP_RESTORED,
    "Air healing": enums.WeaponEffectType.AIR_HEALING,
    "Earth healing": enums.WeaponEffectType.EARTH_HEALING,
    "Fire healing": enums.WeaponEffectType.FIRE_HEALING,
    "Water healing": enums.WeaponEffectType.WATER_HEALING,
    "Neutral healing": enums.WeaponEffectType.NEUTRAL_HEALING,
    "Best element damage": enums.WeaponEffectType.BEST_ELEMENT_DAMAGE,
    "Best element steal": enums.WeaponEffectType.BEST_ELEMENT_STEAL,
    "Pushback damage": enums.WeaponEffectType.PUSHBACK_DAMAGE,
    "Attract cells": enums.WeaponEffectType.ATTRACT_CELLS,
    "Steals MP": enums.WeaponEffectType.STEALS_MP,
}

to_spell_enum = {
    "Neutral damage": enums.SpellEffectType.NEUTRAL_DAMAGE,
    "Earth damage": enums.SpellEffectType.EARTH_DAMAGE,
    "Fire damage": enums.SpellEffectType.FIRE_DAMAGE,
    "Water damage": enums.SpellEffectType.WATER_DAMAGE,
    "Air damage": enums.SpellEffectType.AIR_DAMAGE,
    "Neutral steal": enums.SpellEffectType.NEUTRAL_STEAL,
    "Earth steal": enums.SpellEffectType.EARTH_STEAL,
    "Fire steal": enums.SpellEffectType.FIRE_STEAL,
    "Water steal": enums.SpellEffectType.WATER_STEAL,
    "Air steal": enums.SpellEffectType.AIR_STEAL,
    "HP restored": enums.SpellEffectType.HP_RESTORED,
    "Shield": enums.SpellEffectType.SHIELD,
    "Pushback damage": enums.SpellEffectType.PUSHBACK_DAMAGE,
    "Best element damage": enums.SpellEffectType.BEST_ELEMENT_DAMAGE,
    "Best element steal": enums.SpellEffectType.BEST_ELEMENT_STEAL,
    "Best element healing": enums.SpellEffectType.BEST_ELEMENT_HEALING,
    "Air healing": enums.SpellEffectType.AIR_HEALING,
    "Earth healing": enums.SpellEffectType.EARTH_HEALING,
    "Fire healing": enums.SpellEffectType.FIRE_HEALING,
    "Water healing": enums.SpellEffectType.WATER_HEALING,
    "Neutral healing": enums.SpellEffectType.NEUTRAL_HEALING,
}
