"""Create local DofusLab builds from build-discovery prototype output.

Run inside the server container:

    python -m oneoff.import_build_discovery_candidates --limit 3
"""

from __future__ import annotations

import argparse
from datetime import datetime
from typing import Iterable

from app import session_scope
from app.database.enums import BuildGender
from app.database.model_class_translation import ModelClassTranslation
from app.database.model_custom_set import MAX_NAME_LENGTH, ModelCustomSet
from app.database.model_custom_set_stat import ModelCustomSetStat
from app.database.model_item import ModelItem
from oneoff.build_discovery_prototype import (
    DEFAULT_MAX_SHARED_ITEMS,
    DEFAULT_TARGET,
    TARGET_LEVEL,
    BuildTarget,
    find_diverse_builds,
)


DEFAULT_BASE_URL = "http://localhost:8080"


def get_iop_class_id(db_session):
    translation = (
        db_session.query(ModelClassTranslation)
        .filter_by(locale="en", name="Iop")
        .one_or_none()
    )
    return translation.class_id if translation else None


def item_ids_for_build(build) -> list[str]:
    return [item["dofusID"] for item in build.slots.values()]


def get_items_by_dofus_id(db_session, dofus_ids: Iterable[str]) -> dict[str, ModelItem]:
    items = (
        db_session.query(ModelItem)
        .filter(ModelItem.dofus_db_id.in_(list(dofus_ids)))
        .all()
    )
    return {item.dofus_db_id: item for item in items}


def missing_item_ids_for_build(db_session, build) -> list[str]:
    dofus_ids = item_ids_for_build(build)
    items_by_dofus_id = get_items_by_dofus_id(db_session, dofus_ids)
    return [dofus_id for dofus_id in dofus_ids if dofus_id not in items_by_dofus_id]


def create_custom_set_from_build(db_session, build, index: int, name_prefix: str):
    dofus_ids = item_ids_for_build(build)
    items_by_dofus_id = get_items_by_dofus_id(db_session, dofus_ids)
    missing_ids = [dofus_id for dofus_id in dofus_ids if dofus_id not in items_by_dofus_id]
    if missing_ids:
        raise RuntimeError(f"Missing imported items in database: {', '.join(missing_ids)}")

    custom_set = ModelCustomSet(
        name=f"{name_prefix} #{index}"[:MAX_NAME_LENGTH],
        level=TARGET_LEVEL,
        owner_id=None,
        build_gender=BuildGender.MALE,
        default_class_id=get_iop_class_id(db_session),
        description=(
            "Generated by oneoff.import_build_discovery_candidates. "
            "Prototype scoring is rough; use this for inspection only."
        ),
    )
    db_session.add(custom_set)
    db_session.flush()

    stats = ModelCustomSetStat(
        custom_set_id=custom_set.uuid,
        base_strength=300,
        base_vitality=395,
        scrolled_strength=100,
        scrolled_vitality=100,
        scrolled_wisdom=100,
        scrolled_intelligence=100,
        scrolled_chance=100,
        scrolled_agility=100,
    )
    db_session.add(stats)
    db_session.flush()

    custom_set.equip_items(
        [{"item": items_by_dofus_id[dofus_id]} for dofus_id in dofus_ids],
        db_session,
    )
    custom_set.last_modified = datetime.utcnow()
    return custom_set


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=3)
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--name-prefix", default="Prototype Strength Iop")
    parser.add_argument("--top-k", type=int, default=25)
    parser.add_argument("--beam-width", type=int, default=250)
    parser.add_argument("--target-ap", type=int, default=DEFAULT_TARGET.ap)
    parser.add_argument("--target-mp", type=int, default=DEFAULT_TARGET.mp)
    parser.add_argument("--target-range", type=int, default=DEFAULT_TARGET.range)
    parser.add_argument("--max-shared-items", type=int, default=DEFAULT_MAX_SHARED_ITEMS)
    args = parser.parse_args()

    target = BuildTarget(ap=args.target_ap, mp=args.target_mp, range=args.target_range)
    builds = find_diverse_builds(
        limit=args.limit,
        top_k=args.top_k,
        beam_width=args.beam_width,
        per_signature_cap=40,
        relevant_set_limit=60,
        target=target,
        max_shared_items=args.max_shared_items,
    )

    if not builds:
        raise RuntimeError("No prototype builds were generated.")

    base_url = args.base_url.rstrip("/")
    created = []
    skipped = []
    with session_scope() as db_session:
        for build in builds:
            missing_ids = missing_item_ids_for_build(db_session, build)
            if missing_ids:
                skipped.append(missing_ids)
                continue

            custom_set = create_custom_set_from_build(
                db_session,
                build,
                len(created) + 1,
                args.name_prefix,
            )
            created.append(
                {
                    "name": custom_set.name,
                    "id": str(custom_set.uuid),
                    "build_url": f"{base_url}/build/{custom_set.uuid}/",
                    "view_url": f"{base_url}/view/{custom_set.uuid}/",
                }
            )
            if len(created) >= args.limit:
                break

    if not created:
        raise RuntimeError("No generated builds could be imported with the local database items.")

    print("Created prototype builds:")
    for build in created:
        print(f"- {build['name']}")
        print(f"  Build: {build['build_url']}")
        print(f"  View:  {build['view_url']}")
    if skipped:
        print("Skipped generated builds with missing local item ids:")
        for missing_ids in skipped:
            print(f"- {', '.join(missing_ids)}")


if __name__ == "__main__":
    main()
