"""empty message

Revision ID: 04b11423b6b9
Revises: 4cd3cd64a0de
Create Date: 2020-05-28 18:47:33.392429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "04b11423b6b9"
down_revision = "4fe2cac55fe5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buff",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("item_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("spell_stat_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "stat",
            postgresql.ENUM(
                "VITALITY",
                "AP",
                "MP",
                "INITIATIVE",
                "PROSPECTING",
                "RANGE",
                "SUMMON",
                "WISDOM",
                "STRENGTH",
                "INTELLIGENCE",
                "CHANCE",
                "AGILITY",
                "AP_PARRY",
                "AP_REDUCTION",
                "MP_PARRY",
                "MP_REDUCTION",
                "CRITICAL",
                "HEALS",
                "LOCK",
                "DODGE",
                "PCT_FINAL_DAMAGE",
                "POWER",
                "DAMAGE",
                "CRITICAL_DAMAGE",
                "NEUTRAL_DAMAGE",
                "EARTH_DAMAGE",
                "FIRE_DAMAGE",
                "WATER_DAMAGE",
                "AIR_DAMAGE",
                "REFLECT",
                "TRAP_DAMAGE",
                "TRAP_POWER",
                "PUSHBACK_DAMAGE",
                "PCT_SPELL_DAMAGE",
                "PCT_WEAPON_DAMAGE",
                "PCT_RANGED_DAMAGE",
                "PCT_MELEE_DAMAGE",
                "NEUTRAL_RES",
                "PCT_NEUTRAL_RES",
                "EARTH_RES",
                "PCT_EARTH_RES",
                "FIRE_RES",
                "PCT_FIRE_RES",
                "WATER_RES",
                "PCT_WATER_RES",
                "AIR_RES",
                "PCT_AIR_RES",
                "CRITICAL_RES",
                "PUSHBACK_RES",
                "PCT_RANGED_RES",
                "PCT_MELEE_RES",
                "PODS",
                name="stat",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("increment_by", sa.Integer(), nullable=True),
        sa.Column("max_stacks", sa.Integer(), nullable=True),
        sa.Column("crit_increment_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.uuid"], name=op.f("fk_buff_item_id_item")
        ),
        sa.ForeignKeyConstraint(
            ["spell_stat_id"],
            ["spell_stats.uuid"],
            name=op.f("fk_buff_spell_stat_id_spell_stats"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_buff")),
        sa.UniqueConstraint("uuid", name=op.f("uq_buff_uuid")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("buff")
    # ### end Alembic commands ###
