"""empty message

Revision ID: 06c1e15ce9ee
Revises: 99a50103e080
Create Date: 2020-09-03 23:51:40.454652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "06c1e15ce9ee"
down_revision = "99a50103e080"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_set",
        sa.Column("default_class_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_index(
        op.f("ix_custom_set_default_class_id"),
        "custom_set",
        ["default_class_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_custom_set_default_class_id_class"),
        "custom_set",
        "class",
        ["default_class_id"],
        ["uuid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_custom_set_default_class_id_class"), "custom_set", type_="foreignkey"
    )
    op.drop_index(op.f("ix_custom_set_default_class_id"), table_name="custom_set")
    op.drop_column("custom_set", "default_class_id")
    # ### end Alembic commands ###
