"""empty message

Revision ID: 07c10082cc7f
Revises: 7783111dc49f
Create Date: 2020-05-26 18:58:34.781201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07c10082cc7f"
down_revision = "7783111dc49f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spell_stats", "has_default_condition")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spell_stats",
        sa.Column(
            "has_default_condition", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
