"""empty message

Revision ID: 0ab103094fe7
Revises: e754dc048376
Create Date: 2024-10-19 13:20:22.156946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab103094fe7'
down_revision = 'e754dc048376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_set', sa.Column('private', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    res = conn.execute("SELECT uuid, private FROM custom_set")
    custom_sets = res.fetchall()
    for custom_set in custom_sets:
        conn.execute(
            "UPDATE custom_set SET private = '{}' WHERE uuid='{}'".format(
                False, custom_set[0]
            )
        )
    op.alter_column('custom_set', 'private', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_set', 'private')
    # ### end Alembic commands ###
