"""empty message

Revision ID: 138ae7ddca87
Revises: 297004946fea
Create Date: 2020-03-02 23:50:44.344740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138ae7ddca87'
down_revision = '297004946fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_set', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_custom_set_last_modified'), 'custom_set', ['last_modified'], unique=False)
    op.create_index(op.f('ix_equipped_item_item_slot_id'), 'equipped_item', ['item_slot_id'], unique=False)
    op.create_unique_constraint(op.f('uq_equipped_item_item_slot_id'), 'equipped_item', ['item_slot_id', 'custom_set_id'])
    op.drop_constraint('equipped_item_slot', 'equipped_item', type_='unique')
    op.create_unique_constraint(op.f('uq_item_type_slot_item_slot_id'), 'item_type_slot', ['item_slot_id', 'item_type_id'])
    op.drop_constraint('item_type_slot_compatibility', 'item_type_slot', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('item_type_slot_compatibility', 'item_type_slot', ['item_slot_id', 'item_type_id'])
    op.drop_constraint(op.f('uq_item_type_slot_item_slot_id'), 'item_type_slot', type_='unique')
    op.create_unique_constraint('equipped_item_slot', 'equipped_item', ['item_slot_id', 'custom_set_id'])
    op.drop_constraint(op.f('uq_equipped_item_item_slot_id'), 'equipped_item', type_='unique')
    op.drop_index(op.f('ix_equipped_item_item_slot_id'), table_name='equipped_item')
    op.drop_index(op.f('ix_custom_set_last_modified'), table_name='custom_set')
    op.drop_column('custom_set', 'last_modified')
    # ### end Alembic commands ###
