"""empty message

Revision ID: 18b7d0f5c9ff
Revises: 285b17b32c4e
Create Date: 2020-03-05 00:16:04.832703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18b7d0f5c9ff"
down_revision = "285b17b32c4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_set_stat",
        "base_agility",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "base_chance",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "base_intelligence",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "base_strength",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "base_vitality",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "base_wisdom",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_agility",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_chance",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_intelligence",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_strength",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_vitality",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_wisdom",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_set_stat", "scrolled_wisdom", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_vitality",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_strength",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "custom_set_stat",
        "scrolled_intelligence",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "custom_set_stat", "scrolled_chance", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "custom_set_stat", "scrolled_agility", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "custom_set_stat", "base_wisdom", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "custom_set_stat", "base_vitality", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "custom_set_stat", "base_strength", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "custom_set_stat",
        "base_intelligence",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "custom_set_stat", "base_chance", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "custom_set_stat", "base_agility", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
