"""empty message

Revision ID: 297004946fea
Revises: a2701c0cdab7
Create Date: 2020-02-23 20:26:37.803067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "297004946fea"
down_revision = "a2701c0cdab7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password", sa.LargeBinary(length=120), nullable=False)
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.VARCHAR(),
        type_=sa.String(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "username",
        existing_type=sa.VARCHAR(),
        type_=sa.String(length=120),
        existing_nullable=False,
    )
    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    op.create_unique_constraint(op.f("uq_user_username"), "user", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_username"), "user", type_="unique")
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.alter_column(
        "user",
        "username",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "email",
        existing_type=sa.String(length=320),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("user", "password")
    # ### end Alembic commands ###
