"""empty message

Revision ID: 2c43533cea2a
Revises: 12db69ebed11
Create Date: 2020-04-27 22:20:07.615515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c43533cea2a'
down_revision = '12db69ebed11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_class_translation_class_id'), 'class_translation', ['class_id', 'locale'])
    op.create_unique_constraint(op.f('uq_item_slot_translation_id'), 'item_slot_translation', ['id'])
    op.create_unique_constraint(op.f('uq_item_slot_translation_item_slot_id'), 'item_slot_translation', ['item_slot_id', 'locale'])
    op.create_unique_constraint(op.f('uq_item_stat_translation_item_stat_id'), 'item_stat_translation', ['item_stat_id', 'locale'])
    op.create_unique_constraint(op.f('uq_item_translation_item_id'), 'item_translation', ['item_id', 'locale'])
    op.create_unique_constraint(op.f('uq_item_type_translation_id'), 'item_type_translation', ['id'])
    op.create_unique_constraint(op.f('uq_item_type_translation_item_type_id'), 'item_type_translation', ['item_type_id', 'locale'])
    op.create_unique_constraint(op.f('uq_set_bonus_translation_set_bonus_id'), 'set_bonus_translation', ['set_bonus_id', 'locale'])
    op.create_unique_constraint(op.f('uq_set_translation_set_id'), 'set_translation', ['set_id', 'locale'])
    op.create_unique_constraint(op.f('uq_spell_stat_translation_spell_stat_id'), 'spell_stat_translation', ['spell_stat_id', 'locale'])
    op.create_unique_constraint(op.f('uq_spell_translation_spell_id'), 'spell_translation', ['spell_id', 'locale'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_spell_translation_spell_id'), 'spell_translation', type_='unique')
    op.drop_constraint(op.f('uq_spell_stat_translation_spell_stat_id'), 'spell_stat_translation', type_='unique')
    op.drop_constraint(op.f('uq_set_translation_set_id'), 'set_translation', type_='unique')
    op.drop_constraint(op.f('uq_set_bonus_translation_set_bonus_id'), 'set_bonus_translation', type_='unique')
    op.drop_constraint(op.f('uq_item_type_translation_item_type_id'), 'item_type_translation', type_='unique')
    op.drop_constraint(op.f('uq_item_type_translation_id'), 'item_type_translation', type_='unique')
    op.drop_constraint(op.f('uq_item_translation_item_id'), 'item_translation', type_='unique')
    op.drop_constraint(op.f('uq_item_stat_translation_item_stat_id'), 'item_stat_translation', type_='unique')
    op.drop_constraint(op.f('uq_item_slot_translation_item_slot_id'), 'item_slot_translation', type_='unique')
    op.drop_constraint(op.f('uq_item_slot_translation_id'), 'item_slot_translation', type_='unique')
    op.drop_constraint(op.f('uq_class_translation_class_id'), 'class_translation', type_='unique')
    # ### end Alembic commands ###
