"""empty message

Revision ID: 4180ddd14d6a
Revises: 1ada78e59e43
Create Date: 2022-01-06 13:37:02.273804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4180ddd14d6a"
down_revision = "1ada78e59e43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "class", "female_face_image_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column(
        "custom_set",
        sa.Column(
            "build_gender",
            sa.Enum("MALE", "FEMALE", name="buildgender"),
            nullable=True,
        ),
    )
    conn = op.get_bind()
    conn.execute("UPDATE custom_set SET build_gender='MALE'")
    res = conn.execute(
        """SELECT ua.uuid, us.build_gender FROM user_setting us
        JOIN user_account ua ON ua.uuid = us.user_id
        """
    )
    users = res.fetchall()
    for user in users:
        conn.execute(
            "UPDATE custom_set SET build_gender='{}' WHERE owner_id='{}'".format(
                user[1], user[0]
            )
        )

    op.alter_column("custom_set", "build_gender", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_set", "build_gender")
    op.alter_column(
        "class", "female_face_image_url", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
