"""empty message

Revision ID: 4cd3cd64a0de
Revises: 614815cc9eb6
Create Date: 2020-05-15 02:07:26.350221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4cd3cd64a0de"
down_revision = "614815cc9eb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_item",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("item_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.uuid"],
            name=op.f("fk_favorite_item_item_id_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_account_id"],
            ["user_account.uuid"],
            name=op.f("fk_favorite_item_user_account_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_favorite_item")),
        sa.UniqueConstraint(
            "user_account_id", "item_id", name=op.f("uq_favorite_item_user_account_id")
        ),
    )
    op.create_index(
        op.f("ix_favorite_item_item_id"), "favorite_item", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_favorite_item_user_account_id"),
        "favorite_item",
        ["user_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite_item_user_account_id"), table_name="favorite_item")
    op.drop_index(op.f("ix_favorite_item_item_id"), table_name="favorite_item")
    op.drop_table("favorite_item")
    # ### end Alembic commands ###
