"""empty message

Revision ID: 4fe2cac55fe5
Revises: 07c10082cc7f
Create Date: 2020-06-05 01:28:57.212127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe2cac55fe5'
down_revision = '07c10082cc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spell_effect_has_condition', table_name='spell_effect')
    op.drop_column('spell_effect', 'has_condition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell_effect', sa.Column('has_condition', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_spell_effect_has_condition', 'spell_effect', ['has_condition'], unique=False)
    # ### end Alembic commands ###
