"""empty message

Revision ID: 614815cc9eb6
Revises: cd264bac7b6f
Create Date: 2020-05-10 23:46:47.410468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "614815cc9eb6"
down_revision = "cd264bac7b6f"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("COMMIT")
    op.execute("ALTER TYPE spell_effect_type ADD VALUE 'BEST_ELEMENT_DAMAGE'")
    op.execute("ALTER TYPE spell_effect_type ADD VALUE 'BEST_ELEMENT_STEAL'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute(
        "DELETE FROM pg_enum WHERE enumlabel = 'BEST_ELEMENT_DAMAGE' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'spell_effect_type')"
    )
    op.execute(
        "DELETE FROM pg_enum WHERE enumlabel = 'BEST_ELEMENT_STEAL' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'spell_effect_type')"
    )
    # ### end Alembic commands ###
