"""empty message

Revision ID: 7783111dc49f
Revises: ead98a8d1d65
Create Date: 2020-05-26 02:37:23.559061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7783111dc49f"
down_revision = "ead98a8d1d65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spell_effect_condition_translation",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("spell_effect_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spell_effect_id"],
            ["spell_effect.uuid"],
            name=op.f(
                "fk_spell_effect_condition_translation_spell_effect_id_spell_effect"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "uuid", name=op.f("pk_spell_effect_condition_translation")
        ),
    )
    op.create_index(
        op.f("ix_spell_effect_condition_translation_locale"),
        "spell_effect_condition_translation",
        ["locale"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spell_effect_condition_translation_spell_effect_id"),
        "spell_effect_condition_translation",
        ["spell_effect_id"],
        unique=False,
    )
    op.create_index(
        "spell_effect_id",
        "spell_effect_condition_translation",
        ["locale"],
        unique=False,
    )
    op.add_column(
        "spell_effect", sa.Column("has_condition", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE spell_effect SET has_condition = false")
    op.alter_column("spell_effect", "has_condition", nullable=False)
    op.add_column("spell_effect", sa.Column("order", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_spell_effect_has_condition"),
        "spell_effect",
        ["has_condition"],
        unique=False,
    )
    op.add_column(
        "spell_stats", sa.Column("has_default_condition", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spell_stats", "has_default_condition")
    op.drop_index(op.f("ix_spell_effect_has_condition"), table_name="spell_effect")
    op.drop_column("spell_effect", "order")
    op.drop_column("spell_effect", "has_condition")
    op.drop_index("spell_effect_id", table_name="spell_effect_condition_translation")
    op.drop_index(
        op.f("ix_spell_effect_condition_translation_spell_effect_id"),
        table_name="spell_effect_condition_translation",
    )
    op.drop_index(
        op.f("ix_spell_effect_condition_translation_locale"),
        table_name="spell_effect_condition_translation",
    )
    op.drop_table("spell_effect_condition_translation")
    # ### end Alembic commands ###
