"""empty message

Revision ID: 7891b49e562c
Revises: 60f02d588ac3
Create Date: 2020-03-30 12:58:02.536438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7891b49e562c"
down_revision = "60f02d588ac3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_class_uuid"), "class", ["uuid"])
    op.create_unique_constraint(
        op.f("uq_class_translation_id"), "class_translation", ["id"]
    )
    op.create_unique_constraint(op.f("uq_spell_uuid"), "spell", ["uuid"])
    op.create_unique_constraint(
        op.f("uq_spell_variant_pair_uuid"), "spell_variant_pair", ["uuid"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_spell_variant_pair_uuid"), "spell_variant_pair", type_="unique"
    )
    op.drop_constraint(op.f("uq_spell_uuid"), "spell", type_="unique")
    op.drop_constraint(
        op.f("uq_class_translation_id"), "class_translation", type_="unique"
    )
    op.drop_constraint(op.f("uq_class_uuid"), "class", type_="unique")
    # ### end Alembic commands ###
