"""empty message

Revision ID: 8b23da1cb2e1
Revises: 381785d20acf
Create Date: 2020-12-25 21:32:36.162925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b23da1cb2e1"
down_revision = "381785d20acf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_item_slot_translation_item_slot_id_item_slot",
        "item_slot_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_item_slot_translation_item_slot_id_item_slot"),
        "item_slot_translation",
        "item_slot",
        ["item_slot_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_item_type_translation_item_type_id_item_type",
        "item_type_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_item_type_translation_item_type_id_item_type"),
        "item_type_translation",
        "item_type",
        ["item_type_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_item_type_translation_item_type_id_item_type"),
        "item_type_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_item_type_translation_item_type_id_item_type",
        "item_type_translation",
        "item_type",
        ["item_type_id"],
        ["uuid"],
    )
    op.drop_constraint(
        op.f("fk_item_slot_translation_item_slot_id_item_slot"),
        "item_slot_translation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_item_slot_translation_item_slot_id_item_slot",
        "item_slot_translation",
        "item_slot",
        ["item_slot_id"],
        ["uuid"],
    )
    # ### end Alembic commands ###
