"""empty message

Revision ID: 959cd507155b
Revises: 6d5e10e2995e
Create Date: 2020-03-13 00:04:35.166241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "959cd507155b"
down_revision = "6d5e10e2995e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weapon_stat",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("item_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("ap_cost", sa.Integer(), nullable=False),
        sa.Column("uses_per_turn", sa.Integer(), nullable=False),
        sa.Column("min_range", sa.Integer(), nullable=True),
        sa.Column("max_range", sa.Integer(), nullable=False),
        sa.Column("base_crit_chance", sa.Integer(), nullable=False),
        sa.Column("crit_bonus_damage", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.uuid"], name=op.f("fk_weapon_stat_item_id_item")
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_weapon_stat")),
    )
    op.create_table(
        "weapon_effect",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("weapon_stat_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "effect_type",
            sa.Enum(
                "NEUTRAL_DAMAGE",
                "EARTH_DAMAGE",
                "FIRE_DAMAGE",
                "WATER_DAMAGE",
                "AIR_DAMAGE",
                "NEUTRAL_STEAL",
                "EARTH_STEAL",
                "FIRE_STEAL",
                "WATER_STEAL",
                "AIR_STEAL",
                "AP",
                "MP",
                "HP_RESTORED",
                name="weapon_effect_type",
            ),
            nullable=False,
        ),
        sa.Column("min_damage", sa.Integer(), nullable=True),
        sa.Column("max_damage", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["weapon_stat_id"],
            ["weapon_stat.uuid"],
            name=op.f("fk_weapon_effect_weapon_stat_id_weapon_stat"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_weapon_effect")),
    )
    op.add_column("item", sa.Column("conditions", sa.JSON(), nullable=True))
    op.drop_column("item", "condtions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "condtions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("item", "conditions")
    op.drop_table("weapon_effect")
    op.drop_table("weapon_stat")
    # ### end Alembic commands ###
