"""empty message

Revision ID: 99987f8688c7
Revises: 06c1e15ce9ee
Create Date: 2020-09-11 00:40:27.847928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "99987f8688c7"
down_revision = "06c1e15ce9ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_set_tag",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_custom_set_tag")),
    )
    op.create_table(
        "custom_set_tag_translation",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("custom_set_tag_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["custom_set_tag_id"],
            ["custom_set_tag.uuid"],
            name=op.f("fk_custom_set_tag_translation_custom_set_tag_id_custom_set_tag"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_custom_set_tag_translation")),
    )
    op.create_index("spell_id", "custom_set_tag_translation", ["locale"], unique=False)
    op.create_table(
        "custom_set_tag_association",
        sa.Column("custom_set_tag_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("custom_set_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["custom_set_id"],
            ["custom_set.uuid"],
            name=op.f("fk_custom_set_tag_association_custom_set_id_custom_set"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["custom_set_tag_id"],
            ["custom_set_tag.uuid"],
            name=op.f("fk_custom_set_tag_association_custom_set_tag_id_custom_set_tag"),
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "custom_set_tag_id",
            "custom_set_id",
            name=op.f("uq_custom_set_tag_association_custom_set_tag_id"),
        ),
    )
    op.create_index(
        op.f("ix_custom_set_tag_association_custom_set_id"),
        "custom_set_tag_association",
        ["custom_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custom_set_tag_association_custom_set_tag_id"),
        "custom_set_tag_association",
        ["custom_set_tag_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_custom_set_tag_association_custom_set_tag_id"),
        table_name="custom_set_tag_association",
    )
    op.drop_index(
        op.f("ix_custom_set_tag_association_custom_set_id"),
        table_name="custom_set_tag_association",
    )
    op.drop_table("custom_set_tag_association")
    op.drop_index("spell_id", table_name="custom_set_tag_translation")
    op.drop_table("custom_set_tag_translation")
    op.drop_table("custom_set_tag")
    # ### end Alembic commands ###
