"""empty message

Revision ID: 99a50103e080
Revises: 04b11423b6b9
Create Date: 2020-06-29 16:01:58.340047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a50103e080'
down_revision = '04b11423b6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_buff_uuid'), 'buff', ['uuid'])
    op.drop_constraint('fk_buff_item_id_item', 'buff', type_='foreignkey')
    op.drop_constraint('fk_buff_spell_stat_id_spell_stats', 'buff', type_='foreignkey')
    op.create_foreign_key(op.f('fk_buff_item_id_item'), 'buff', 'item', ['item_id'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_buff_spell_stat_id_spell_stats'), 'buff', 'spell_stats', ['spell_stat_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_buff_spell_stat_id_spell_stats'), 'buff', type_='foreignkey')
    op.drop_constraint(op.f('fk_buff_item_id_item'), 'buff', type_='foreignkey')
    op.create_foreign_key('fk_buff_spell_stat_id_spell_stats', 'buff', 'spell_stats', ['spell_stat_id'], ['uuid'])
    op.create_foreign_key('fk_buff_item_id_item', 'buff', 'item', ['item_id'], ['uuid'])
    op.drop_constraint(op.f('uq_buff_uuid'), 'buff', type_='unique')
    # ### end Alembic commands ###
