"""empty message

Revision ID: 9ce751fbce98
Revises: 12db69ebed11
Create Date: 2020-04-27 22:39:02.638042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ce751fbce98"
down_revision = "12db69ebed11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("class_id", "class_translation", ["locale"], unique=False)
    op.drop_index("ix_class_translation_class_id", table_name="class_translation")
    op.create_index("item_slot_id", "item_slot_translation", ["locale"], unique=False)
    op.create_unique_constraint(
        op.f("uq_item_slot_translation_id"), "item_slot_translation", ["id"]
    )
    op.create_index("item_stat_id", "item_stat_translation", ["locale"], unique=False)
    op.drop_index(
        "ix_item_stat_translation_item_stat_id", table_name="item_stat_translation"
    )
    op.drop_index("ix_item_stat_translation_locale", table_name="item_stat_translation")
    op.create_index("item_id", "item_translation", ["locale", "name"], unique=False)
    op.drop_index("ix_item_translation_item_id", table_name="item_translation")
    op.drop_index("ix_item_translation_locale", table_name="item_translation")
    op.create_index("item_type_id", "item_type_translation", ["locale"], unique=False)
    op.create_unique_constraint(
        op.f("uq_item_type_translation_id"), "item_type_translation", ["id"]
    )
    op.create_index("set_bonus_id", "set_bonus_translation", ["locale"], unique=False)
    op.drop_index("ix_set_bonus_translation_locale", table_name="set_bonus_translation")
    op.drop_index(
        "ix_set_bonus_translation_set_bonus_id", table_name="set_bonus_translation"
    )
    op.create_index("set_id", "set_translation", ["locale", "name"], unique=False)
    op.drop_index("ix_set_translation_locale", table_name="set_translation")
    op.drop_index("ix_set_translation_name", table_name="set_translation")
    op.drop_index("ix_set_translation_set_id", table_name="set_translation")
    op.create_index("spell_stat_id", "spell_stat_translation", ["locale"], unique=False)
    op.create_index("spell_id", "spell_translation", ["locale"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("spell_id", table_name="spell_translation")
    op.drop_index("spell_stat_id", table_name="spell_stat_translation")
    op.create_index(
        "ix_set_translation_set_id", "set_translation", ["set_id"], unique=False
    )
    op.create_index(
        "ix_set_translation_name", "set_translation", ["name"], unique=False
    )
    op.create_index(
        "ix_set_translation_locale", "set_translation", ["locale"], unique=False
    )
    op.drop_index("set_id", table_name="set_translation")
    op.create_index(
        "ix_set_bonus_translation_set_bonus_id",
        "set_bonus_translation",
        ["set_bonus_id"],
        unique=False,
    )
    op.create_index(
        "ix_set_bonus_translation_locale",
        "set_bonus_translation",
        ["locale"],
        unique=False,
    )
    op.drop_index("set_bonus_id", table_name="set_bonus_translation")
    op.drop_constraint(
        op.f("uq_item_type_translation_id"), "item_type_translation", type_="unique"
    )
    op.drop_index("item_type_id", table_name="item_type_translation")
    op.create_index(
        "ix_item_translation_locale", "item_translation", ["locale"], unique=False
    )
    op.create_index(
        "ix_item_translation_item_id", "item_translation", ["item_id"], unique=False
    )
    op.drop_index("item_id", table_name="item_translation")
    op.create_index(
        "ix_item_stat_translation_locale",
        "item_stat_translation",
        ["locale"],
        unique=False,
    )
    op.create_index(
        "ix_item_stat_translation_item_stat_id",
        "item_stat_translation",
        ["item_stat_id"],
        unique=False,
    )
    op.drop_index("item_stat_id", table_name="item_stat_translation")
    op.drop_constraint(
        op.f("uq_item_slot_translation_id"), "item_slot_translation", type_="unique"
    )
    op.drop_index("item_slot_id", table_name="item_slot_translation")
    op.create_index(
        "ix_class_translation_class_id", "class_translation", ["class_id"], unique=False
    )
    op.drop_index("class_id", table_name="class_translation")
    # ### end Alembic commands ###
