"""empty message

Revision ID: bc6df2e88154
Revises: 47c0338ee9ff
Create Date: 2020-04-23 14:25:40.760534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc6df2e88154"
down_revision = "47c0338ee9ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_item_level"), "item", ["level"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_level"), table_name="item")
    # ### end Alembic commands ###
