"""empty message

Revision ID: dc4e345c7ca5
Revises: 7891b49e562c
Create Date: 2020-03-30 14:18:07.167780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc4e345c7ca5"
down_revision = "7891b49e562c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("creation_date", sa.DateTime(), nullable=True))
    op.add_column(
        "user", sa.Column("verification_email_sent", sa.Boolean(), nullable=False)
    )
    op.add_column("user", sa.Column("verified", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_verified"), "user", ["verified"], unique=False)
    op.drop_constraint("uq_user_email", "user", type_="unique")
    op.drop_constraint("uq_user_username", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_username", "user", ["username"])
    op.create_unique_constraint("uq_user_email", "user", ["email"])
    op.drop_index(op.f("ix_user_verified"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "verified")
    op.drop_column("user", "verification_email_sent")
    op.drop_column("user", "creation_date")
    # ### end Alembic commands ###
