"""empty message

Revision ID: ead98a8d1d65
Revises: 4cd3cd64a0de
Create Date: 2020-05-21 12:51:37.338527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ead98a8d1d65"
down_revision = "4cd3cd64a0de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_item_image_url"), "item", ["image_url"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_image_url"), table_name="item")
    # ### end Alembic commands ###
