"""empty message

Revision ID: ec161262d550
Revises: 101593cfd491
Create Date: 2020-05-10 01:24:06.075844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ec161262d550"
down_revision = "101593cfd491"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spell_damage_increase",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("spell_stat_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("base_increase", sa.Integer(), nullable=False),
        sa.Column("crit_base_increase", sa.Integer(), nullable=True),
        sa.Column("max_stacks", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["spell_stat_id"],
            ["spell_stats.uuid"],
            name=op.f("fk_spell_damage_increase_spell_stat_id_spell_stats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_spell_damage_increase")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spell_damage_increase")
    # ### end Alembic commands ###
