"""empty message

Revision ID: f175244278d9
Revises: b9b68fd74d2a
Create Date: 2024-03-12 10:02:28.673183

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f175244278d9"
down_revision = "b9b68fd74d2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("dofus_db_mount_id", sa.String(), nullable=True))
    op.alter_column("item", "dofus_db_id", existing_type=sa.VARCHAR(), nullable=True)
    conn = op.get_bind()
    res = conn.execute(
        "SELECT item_type_translation.item_type_id, item.* "
        "FROM item "
        "JOIN item_type_translation ON item.item_type_id = item_type_translation.item_type_id "
        "WHERE item_type_translation.locale = 'en' "
        "AND item_type_translation.name = 'Mount';"
    )
    mounts = res.fetchall()
    for mount in mounts:
        conn.execute(
            "UPDATE item "
            "SET dofus_db_mount_id = '{}', dofus_db_id = NULL "
            "WHERE dofus_db_id = '{}' AND item_type_id = '{}';".format(
                mount.dofus_db_id,
                mount.dofus_db_id,
                mount.item_type_id,
            )
        )

    op.create_check_constraint(
        "dofus_id_xor",
        table_name="item",
        schema="public",
        condition="(dofus_db_id IS NULL) <> (dofus_db_mount_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "dofus_id_xor", table_name="item", type_="check", schema="public"
    )

    conn = op.get_bind()
    res = conn.execute(
        "SELECT item_type_translation.item_type_id, item.* "
        "FROM item "
        "JOIN item_type_translation ON item.item_type_id = item_type_translation.item_type_id "
        "WHERE item_type_translation.locale = 'en' "
        "AND item_type_translation.name = 'Mount';"
    )
    mounts = res.fetchall()

    for mount in mounts:
        conn.execute(
            "UPDATE item "
            "SET dofus_db_id = '{}', dofus_db_mount_id = NULL "
            "WHERE dofus_db_mount_id = '{}' AND item_type_id = '{}';".format(
                mount.dofus_db_mount_id,
                mount.dofus_db_mount_id,
                mount.item_type_id,
            )
        )

    op.alter_column("item", "dofus_db_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("item", "dofus_db_mount_id")
    # ### end Alembic commands ###
