"""empty message

Revision ID: f7d96d4b3895
Revises: 2e5815c5369a
Create Date: 2020-04-17 19:27:00.006633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7d96d4b3895"
down_revision = "2e5815c5369a"
branch_labels = None
depends_on = None


url_base = "https://dofus-lab.s3.us-east-2.amazonaws.com/icons/{}.svg"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item_slot", sa.Column("image_url", sa.String(), nullable=True))
    conn = op.get_bind()
    res = conn.execute("select uuid, name from item_slot")
    item_slots = res.fetchall()
    for item_slot in item_slots:
        conn.execute(
            "UPDATE item_slot SET image_url='{}' WHERE uuid='{}'".format(
                url_base.format(item_slot[1]), item_slot[0]
            )
        )
    op.alter_column("item_slot", "image_url", nullable=False)
    op.create_index(
        op.f("ix_user_account_email"), "user_account", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_user_account_username"), "user_account", ["username"], unique=True
    )
    op.create_index(
        op.f("ix_user_account_verified"), "user_account", ["verified"], unique=False
    )
    op.drop_index("ix_user_email", table_name="user_account")
    op.drop_index("ix_user_username", table_name="user_account")
    op.drop_index("ix_user_verified", table_name="user_account")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_verified", "user_account", ["verified"], unique=False)
    op.create_index("ix_user_username", "user_account", ["username"], unique=True)
    op.create_index("ix_user_email", "user_account", ["email"], unique=True)
    op.drop_index(op.f("ix_user_account_verified"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_username"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_email"), table_name="user_account")
    op.drop_column("item_slot", "image_url")
    # ### end Alembic commands ###
