"""empty message

Revision ID: fe8775e9f207
Revises: dc4e345c7ca5
Create Date: 2020-04-02 00:26:15.027422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe8775e9f207"
down_revision = "dc4e345c7ca5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_set_bonus_translation_locale"),
        "set_bonus_translation",
        ["locale"],
        unique=False,
    )
    op.create_index(
        op.f("ix_set_bonus_translation_set_bonus_id"),
        "set_bonus_translation",
        ["set_bonus_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_set_bonus_translation_set_bonus_id"),
        table_name="set_bonus_translation",
    )
    op.drop_index(
        op.f("ix_set_bonus_translation_locale"), table_name="set_bonus_translation"
    )
    # ### end Alembic commands ###
