"""empty message

Revision ID: 81f1b88a96c7
Revises: 08f4a37b0df6
Create Date: 2020-02-17 18:41:56.369124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '81f1b88a96c7'
down_revision = '08f4a37b0df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    stat_enum = sa.Enum('VITALITY', 'AP', 'MP', 'INITIATIVE', 'PROSPECTING', 'RANGE', 'SUMMON', 'WISDOM', 'STRENGTH', 'INTELLIGENCE', 'CHANCE', 'AGILITY', 'AP_PARRY', 'AP_REDUCTION', 'MP_PARRY', 'MP_REDUCTION', 'CRITICAL', 'HEALS', 'LOCK', 'DODGE', 'PCT_FINAL_DAMAGE', 'POWER', 'CRITICAL_DAMAGE', 'NEUTRAL_DAMAGE', 'EARTH_DAMAGE', 'FIRE_DAMAGE', 'WATER_DAMAGE', 'AIR_DAMAGE',
                        'REFLECT', 'TRAP_DAMAGE', 'TRAP_POWER', 'PUSHBACK_DAMAGE', 'PCT_SPELL_DAMAGE', 'PCT_WEAPON_DAMAGE', 'PCT_RANGED_DAMAGE', 'PCT_MELEE_DAMAGE', 'NEUTRAL_RES', 'PCT_NEUTRAL_RES', 'EARTH_RES', 'PCT_EARTH_RES', 'FIRE_RES', 'PCT_FIRE_RES', 'WATER_RES', 'PCT_WATER_RES', 'AIR_RES', 'PCT_AIR_RES', 'CRITICAL_RES', 'PUSHBACK_RES', 'PCT_RANGED_RES', 'PCT_MELEE_RES', name='stat')
    stat_pg_enum = postgresql.ENUM('VITALITY', 'AP', 'MP', 'INITIATIVE', 'PROSPECTING', 'RANGE', 'SUMMON', 'WISDOM', 'STRENGTH', 'INTELLIGENCE', 'CHANCE', 'AGILITY', 'AP_PARRY', 'AP_REDUCTION', 'MP_PARRY', 'MP_REDUCTION', 'CRITICAL', 'HEALS', 'LOCK', 'DODGE', 'PCT_FINAL_DAMAGE', 'POWER', 'CRITICAL_DAMAGE', 'NEUTRAL_DAMAGE', 'EARTH_DAMAGE', 'FIRE_DAMAGE', 'WATER_DAMAGE', 'AIR_DAMAGE',
                                   'REFLECT', 'TRAP_DAMAGE', 'TRAP_POWER', 'PUSHBACK_DAMAGE', 'PCT_SPELL_DAMAGE', 'PCT_WEAPON_DAMAGE', 'PCT_RANGED_DAMAGE', 'PCT_MELEE_DAMAGE', 'NEUTRAL_RES', 'PCT_NEUTRAL_RES', 'EARTH_RES', 'PCT_EARTH_RES', 'FIRE_RES', 'PCT_FIRE_RES', 'WATER_RES', 'PCT_WATER_RES', 'AIR_RES', 'PCT_AIR_RES', 'CRITICAL_RES', 'PUSHBACK_RES', 'PCT_RANGED_RES', 'PCT_MELEE_RES', name='stat')
    stat_pg_enum.create(op.get_bind())
    # op.alter_column('custom_set_exo', 'stat',
    #                 existing_type=sa.VARCHAR(),
    #                 type_=stat_enum,
    #                 existing_nullable=True,
    #                 postgresql_using='stat::stat')
    # op.alter_column('item_stat', 'stat',
    #                 existing_type=sa.VARCHAR(),
    #                 type_=stat_enum,
    #                 existing_nullable=True,
    #                 postgresql_using='stat::stat')
    op.drop_column('custom_set_exo', 'stat')
    op.drop_column('item_stat', 'stat')
    op.add_column('custom_set_exo',
                  sa.Column('stat', stat_enum, nullable=False))
    op.add_column('item_stat',
                  sa.Column('stat', stat_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    stat_enum = sa.Enum('VITALITY', 'AP', 'MP', 'INITIATIVE', 'PROSPECTING', 'RANGE', 'SUMMON', 'WISDOM', 'STRENGTH', 'INTELLIGENCE', 'CHANCE', 'AGILITY', 'AP_PARRY', 'AP_REDUCTION', 'MP_PARRY', 'MP_REDUCTION', 'CRITICAL', 'HEALS', 'LOCK', 'DODGE', 'PCT_FINAL_DAMAGE', 'POWER', 'CRITICAL_DAMAGE', 'NEUTRAL_DAMAGE', 'EARTH_DAMAGE', 'FIRE_DAMAGE', 'WATER_DAMAGE', 'AIR_DAMAGE',
                        'REFLECT', 'TRAP_DAMAGE', 'TRAP_POWER', 'PUSHBACK_DAMAGE', 'PCT_SPELL_DAMAGE', 'PCT_WEAPON_DAMAGE', 'PCT_RANGED_DAMAGE', 'PCT_MELEE_DAMAGE', 'NEUTRAL_RES', 'PCT_NEUTRAL_RES', 'EARTH_RES', 'PCT_EARTH_RES', 'FIRE_RES', 'PCT_FIRE_RES', 'WATER_RES', 'PCT_WATER_RES', 'AIR_RES', 'PCT_AIR_RES', 'CRITICAL_RES', 'PUSHBACK_RES', 'PCT_RANGED_RES', 'PCT_MELEE_RES', name='stat')

    op.drop_column('custom_set_exo', 'stat')
    op.drop_column('item_stat', 'stat')
    op.add_column('custom_set_exo',
                  sa.Column('stat', sa.String))
    op.add_column('item_stat',
                  sa.Column('stat', sa.String))

    stat_pg_enum = postgresql.ENUM('VITALITY', 'AP', 'MP', 'INITIATIVE', 'PROSPECTING', 'RANGE', 'SUMMON', 'WISDOM', 'STRENGTH', 'INTELLIGENCE', 'CHANCE', 'AGILITY', 'AP_PARRY', 'AP_REDUCTION', 'MP_PARRY', 'MP_REDUCTION', 'CRITICAL', 'HEALS', 'LOCK', 'DODGE', 'PCT_FINAL_DAMAGE', 'POWER', 'CRITICAL_DAMAGE', 'NEUTRAL_DAMAGE', 'EARTH_DAMAGE', 'FIRE_DAMAGE', 'WATER_DAMAGE', 'AIR_DAMAGE',
                                   'REFLECT', 'TRAP_DAMAGE', 'TRAP_POWER', 'PUSHBACK_DAMAGE', 'PCT_SPELL_DAMAGE', 'PCT_WEAPON_DAMAGE', 'PCT_RANGED_DAMAGE', 'PCT_MELEE_DAMAGE', 'NEUTRAL_RES', 'PCT_NEUTRAL_RES', 'EARTH_RES', 'PCT_EARTH_RES', 'FIRE_RES', 'PCT_FIRE_RES', 'WATER_RES', 'PCT_WATER_RES', 'AIR_RES', 'PCT_AIR_RES', 'CRITICAL_RES', 'PUSHBACK_RES', 'PCT_RANGED_RES', 'PCT_MELEE_RES', name='stat')
    stat_pg_enum.drop(op.get_bind())
    # ### end Alembic commands ###
