"""empty message

Revision ID: a2701c0cdab7
Revises: 90eccf39ebb0
Create Date: 2020-02-23 12:28:45.105999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2701c0cdab7"
down_revision = "90eccf39ebb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_set_bonus_set_id_set", "set_bonus", type_="foreignkey")
    op.create_foreign_key(
        None, "set_bonus", "set", ["set_id"], ["uuid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "set_bonus", type_="foreignkey")
    op.create_foreign_key(
        "fk_set_bonus_set_id_set", "set_bonus", "set", ["set_id"], ["uuid"]
    )
    # ### end Alembic commands ###
