"""empty message

Revision ID: b7472d892ad9
Revises: 4e7f099d776b
Create Date: 2020-02-20 10:34:39.579965

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_enum_list
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b7472d892ad9"
down_revision = "4e7f099d776b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_slot",
        sa.Column(
            "uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("item_types", sqlalchemy_enum_list.EnumSetType(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "custom_set_item",
        sa.Column("item_slot_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("custom_set_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("item_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["custom_set_id"], ["custom_set.uuid"],),
        sa.ForeignKeyConstraint(["item_id"], ["item.uuid"],),
        sa.ForeignKeyConstraint(["item_slot_id"], ["item_slot.uuid"],),
        sa.UniqueConstraint("item_slot_id", "custom_set_id"),
    )
    op.create_index(
        op.f("ix_custom_set_item_custom_set_id"),
        "custom_set_item",
        ["custom_set_id"],
        unique=False,
    )
    op.alter_column(
        "item",
        "item_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "HAT",
            "CLOAK",
            "AMULET",
            "RING",
            "BELT",
            "BOOTS",
            "AXE",
            "BOW",
            "DAGGER",
            "HAMMER",
            "PICKAXE",
            "SCYTHE",
            "SHOVEL",
            "STAFF",
            "SWORD",
            "TOOL",
            "WAND",
            "SHIELD",
            "DOFUS",
            "TROPHY",
            "PRYSMARADITE",
            "PET",
            "PETSMOUNT",
            "MOUNT",
            name="itemtype",
        ),
        existing_nullable=False,
    )
    op.drop_constraint("item_custom_set_id_fkey", "item", type_="foreignkey")
    op.drop_column("item", "custom_set_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "custom_set_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "item_custom_set_id_fkey", "item", "custom_set", ["custom_set_id"], ["uuid"]
    )
    op.alter_column(
        "item",
        "item_type",
        existing_type=sa.Enum(
            "HAT",
            "CLOAK",
            "AMULET",
            "RING",
            "BELT",
            "BOOTS",
            "AXE",
            "BOW",
            "DAGGER",
            "HAMMER",
            "PICKAXE",
            "SCYTHE",
            "SHOVEL",
            "STAFF",
            "SWORD",
            "TOOL",
            "WAND",
            "SHIELD",
            "DOFUS",
            "TROPHY",
            "PRYSMARADITE",
            "PET",
            "PETSMOUNT",
            "MOUNT",
            name="itemtype",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_custom_set_item_custom_set_id"), table_name="custom_set_item"
    )
    op.drop_table("custom_set_item")
    op.drop_table("item_slot")
    # ### end Alembic commands ###
