"""empty message

Revision ID: bd4379b590e5
Revises: 
Create Date: 2019-11-17 22:57:04.616533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd4379b590e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_set', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_set', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('custom_set', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'custom_set', ['id'])
    op.add_column('item', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.alter_column('item', 'item_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'item', ['id'])
    op.add_column('set', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'set', ['id'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'set', type_='unique')
    op.drop_column('set', 'id')
    op.drop_constraint(None, 'item', type_='unique')
    op.alter_column('item', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item', 'item_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('item', 'id')
    op.drop_constraint(None, 'custom_set', type_='unique')
    op.alter_column('custom_set', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_set', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('custom_set', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
